version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: hosting/Dockerfile
      target: postgres-openapi
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  postgrest:
    container_name: ${PROJECT_NAME}-postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3005:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${API_DB}
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      # The database role to use when no client authentication is provided
#      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      - PGRST_DB_ANON_ROLE=${POSTGRES_USER}
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
      # Overrides the old inbuilt OpenAPI with the new extension one
      - PGRST_DB_ROOT_SPEC=callable_root
