-- Default PostgREST OpenAPI Specification

create or replace function get_postgrest_openapi_spec(
  schemas text[],
  server_proxy_uri text default 'http://0.0.0.0:3000',
  version text default null
)
returns jsonb language sql as
$$
select openapi_object(
  openapi := '3.1.0',
  info := openapi_info_object(
    title := coalesce(sd.title, 'PostgREST API'),
    description := coalesce(sd.description, 'This is a dynamic API generated by PostgREST'),
    version := coalesce(version, postgrest_get_version())
  ),
  servers := jsonb_build_array(
    openapi_server_object(
      url := server_proxy_uri
    )
  ),
  paths := '{}',
  components := openapi_components_object(
    schemas := postgrest_tables_to_openapi_schema_components(schemas) || postgrest_composite_types_to_openapi_schema_components(schemas)
  )
)
from postgrest_get_schema_description(schemas[1]) sd;
$$;
