-- Default PostgREST OpenAPI Specification

create or replace function get_postgrest_openapi_spec(
  schemas text[],
  server_proxy_uri text default 'http://0.0.0.0:3000',
  version text default null
)
returns jsonb language sql as
$$
select openapi_object(
  openapi := '3.1.0',
  info := openapi_info_object(
    title := coalesce(sd.title, 'PostgREST API'),
    description := coalesce(sd.description, 'This is a dynamic API generated by PostgREST'),
    -- The document version
    version := 'undefined' -- Really we want to give the user some way to set this, so they can release new versions of their API
  ),
  xsoftware := jsonb_build_array(
    -- The version of the OpenAPI extension
    openapi_x_software_object(
      name := 'OpenAPI',
      version := version,
      description := 'Automatically/dynamically generate an OpenAPI schema for the API generated by PostgREST'
    ),
    -- The version of PostgREST
    openapi_x_software_object(
      name := 'PostgREST API',
      version := postgrest_get_version(),
      description := 'Automatically/dynamically turns a PostgreSQL database directly into a RESTful API'
    )
  ),
  servers := openapi_server_objects(),
  paths := '{}',
  components := openapi_components_object(
    schemas := postgrest_tables_to_openapi_schema_components(schemas) || postgrest_composite_types_to_openapi_schema_components(schemas)
  )
)
from postgrest_get_schema_description(schemas[1]) sd;
$$;
